reddit-sentiment-analysis-master/reddit_sentiment_analyzer/urls.py
from django.urls import path
from reddit_sentiment_analyzer import views

app_name='reddit_sentiment_analyzer'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('register/', views.register, name="register"),
    path('logout/', views.user_logout, name="logout"),
    path('user_home/', views.user_home, name="user_home"),
    path('brand_list/', views.get_brandlist, name="brand_list"),
    path('chart/<str:brand>/', views.show, name='chart'),
    path('pause_topic/<str:topic_name>/', views.pause_topic, name='pause_topic'),
    path('delete_topic/<str:topic_name>/', views.delete_topic, name='delete_topic'),
    path(r'trendline/', views.generate_trendline, name="trendline"),
    path(r'trendline/<str:topic_name>/', views.generate_trendline, name="trendline")
]

reddit-sentiment-analysis-master/reddit_sentiment_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reddit_sentiment_analyzer.urls'))
]

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/models.py
from django.db import models

# Create your models here.

class Tweet(models.Model):
    topic_name = models.CharField(max_length=255)
    twitter_handle = models.CharField(max_length=255)
    posting_date = models.DateTimeField()
    message = models.TextField()

    def __str__(self):
        return self.tweet_id
    
class LoginUser(models.Model):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=100)

class Topic(models.Model):
    topic_name = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"topic {self.topic_name} is created at {self.created_at} and is {'Active' if self.active else 'not active'}"

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from .models import LoginUser

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'uk-input uk-width-auto'}), label='Username')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'uk-input uk-width-auto'}), label='Password')

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if user is None:
                raise forms.ValidationError('Invalid username or password.')

        return cleaned_data


class RegisterForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'uk-input uk-width-auto'}), label='Username')
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'uk-input uk-width-auto'}), label='Email')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'uk-input uk-width-auto'}), label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'uk-input uk-width-auto'}), label='Confirm Password')

  
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
            email = self.cleaned_data.get('email')
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError("This Email is Already in use!")
            return email
        
    def clean_username(self):
            username = self.cleaned_data.get('username')
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError("This Username is Already in use!")
            return username


class CreateTopicForm(forms.Form):
    topicname = forms.CharField(widget=forms.TextInput(attrs={'class' : 'uk-input uk-width-auto'}), label='Brandname')

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import LoginForm, RegisterForm, CreateTopicForm
from .models import Topic, Tweet, LoginUser
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from reddit_sentiment_analyzer.redditUtils import get_tweets, get_compound
from reddit_sentiment_analyzer.utils import ThreadPool, THREADPOOL_LIMIT, SingletonQueue
from reddit_sentiment_analyzer.workers import create_worker
from reddit_sentiment_analyzer.redditUtils import start_fetching_comments, start_fetching_submissions
from django.utils import timezone
from django.db.models import Sum
from dateutil.relativedelta import relativedelta
from django.db.models import F, ExpressionWrapper, FloatField, Func
from statistics import mean
from django.http import HttpResponse

def register(request):
    register_form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('reddit_sentiment_analyzer:index')
        else:
            print(form.errors)  # Output the form errors to the console for debugging
            msg = "Please enter the Correct Data"
            return render(request, 'register.html', {'register_form': register_form, 'msg': msg})
    else:
        return render(request, 'register.html', {'register_form': register_form})

# Create your views here.
def index(request):
    login_form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('reddit_sentiment_analyzer:user_home')  
        else:
                msg = "Invalid username or password."
                return render(request, 'login.html', {'login_form' : login_form, 'msg' : msg})

    else:
        form = LoginForm()
    
    return render(request, 'login.html', {'login_form' : login_form})

def about(request):
    return render(request, 'about.html')

def user_logout(request):
    logout(request)
    return redirect('reddit_sentiment_analyzer:index')

@login_required
def user_home(request):
    create_topic_form = CreateTopicForm()
    return render(request, 'user_home.html', {'create_topic_form' : create_topic_form})

from django.shortcuts import render, redirect
from .forms import RegisterForm

def register(request):
    register_form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('reddit_sentiment_analyzer:index')  # Redirect on successful registration
        else:
            msg = "Please enter the Correct Data"
            return render(request, 'register.html', {'register_form': register_form, 'msg': msg})
    else:
        return render(request, 'register.html', {'register_form': register_form})


@login_required
def show(request, brand):
    tweets = get_tweets(brand)
    positive_tweets = [tweet for tweet in tweets if tweet['compound'] > 0.2]
    negative_tweets = [tweet for tweet in tweets if tweet['compound'] < -0.2]
    neutral_tweets = [tweet for tweet in tweets if tweet['compound'] == 0]
    total_tweets = len(tweets)
    positive_sentiment = int((len(positive_tweets) / total_tweets) * 100)
    negative_sentiment = int((len(negative_tweets) / total_tweets) * 100)
    neutral_sentiment = int(100 - (positive_sentiment + negative_sentiment))

    context = {}
    context['sentiment'] = {
        'positive_sentiment': positive_sentiment,
        'negative_sentiment': negative_sentiment,
        'neutral_sentiment': neutral_sentiment
    }
    context['positive_tweets'] = positive_tweets[:5]
    context['negative_tweets'] = negative_tweets[:5]
    context['neutral_tweets'] = neutral_tweets[:5]

    q = SingletonQueue()
    q.stream = True
    return render(request, 'chart.html', context)

@login_required
def get_brandlist(request):
    if request.method == 'POST':
        form = CreateTopicForm(request.POST)
        if form.is_valid():
            topic_name = form.cleaned_data["topicname"]
            create_topic(topic_name)
    topics = Topic.objects.all()
    return render(request, 'brand_list.html', context={'topics': topics})


def get_topics_list():
    topic_list = Topic.objects.all()
    return topic_list

@login_required
def get_trendline(request):
    generate_trendline(request, '')

@login_required
def generate_trendline(request, topic_name=''):
    print("topic_name is ", topic_name)
    options = get_topics_list()
    if topic_name:
        # chart call here
        context = {
            "options": options,
            "selected_option": topic_name,
            "trendline_data": {
                "daily": get_aggregated_data('daily', topic_name),
                "monthly": get_aggregated_data('monthly', topic_name),
                "yearly": get_aggregated_data('yearly', topic_name),
            }
        }
        print(context)
        return render(request, 'trendline.html', context=context)

    return render(request, 'trendline.html', context={"options": options})


def get_aggregated_data(frequency,topic_name):
    # Get the current date
    current_date = timezone.now()

    # Calculate the start date based on the specified frequency
    if frequency == "daily":
        start_date = current_date - relativedelta(days=30)
        date_format = "%b %d, %Y"  # Format for daily labels: "Jun 15, 2023"
    elif frequency == "monthly":
        start_date = current_date - relativedelta(months=12)
        date_format = "%b %Y"  # Format for monthly labels: "Jun 2023"
    elif frequency == "yearly":
        start_date = current_date - relativedelta(years=5)
        date_format = "%Y"  # Format for yearly labels: "2023"
    else:
        raise ValueError("Invalid frequency. Supported frequencies are 'daily', 'monthly', and 'yearly'.")

    # Get all tweet records within the specified timeframe
    tweets = Tweet.objects.filter(posting_date__gte=start_date).filter(topic_name=topic_name.lower())

    tweets = get_compound(tweets)

    tweets.sort(key=lambda tweet: tweet.posting_date)

    result = {}
    current_key = None
    compound_values = []
    for tweet in tweets:
        if tweet.posting_date.strftime(date_format) == current_key:
            compound_values.append(tweet.compound)
        else:
            if current_key is not None:
                result[current_key] = mean(compound_values)
            compound_values = [tweet.compound]
            current_key = tweet.posting_date.strftime(date_format)
    else:
        result[current_key] = mean(compound_values)

    op = {
        'labels':[],
        'data':[]
    }

    for key in result.keys():
        op['labels'].append(key)
        op['data'].append(result[key])

    return op

# def get_topics(request):
#     if request.method == 'POST':
#         topic_name = request.POST.get('topic_name')
#         create_topic(topic_name)
#     topics = Topic.objects.all()
#     return render(request, 'topics.html', context={'topics': topics})

def pause_topic(request, topic_name):
    try:
        topic = Topic.objects.get(topic_name=topic_name)
        topic.active = not topic.active
        topic.save()
        restart_all_workers()
    except Exception as e:
        print("Topic does not exist")
    return HttpResponseRedirect(reverse('reddit_sentiment_analyzer:brand_list'))

def delete_topic(request, topic_name):
    try:
        Topic.objects.get(topic_name=topic_name).delete()
    except Exception as e:
        print("failed to delete topic")
    try:
        Tweet.objects.filter(topic_name=topic_name.lower()).delete()
    except Exception as e:
        print("failed to delete tweets")
    restart_all_workers()
    return HttpResponseRedirect(reverse('reddit_sentiment_analyzer:brand_list'))


def create_topic(topic_name):
    try:
        t = Topic(topic_name=topic_name, created_at=datetime.now(), active=True)
        t.save()
    except Exception as e:
        print(e)
    restart_all_workers()

def restart_all_workers():
    t = ThreadPool()
    q = SingletonQueue()
    t.destroy_all_threads()

    topics = [topic.topic_name.lower() for topic in Topic.objects.all() if topic.active]

    # starting streaming submissions and comments
    t.execute(start_fetching_comments, topics, q)
    t.execute(start_fetching_submissions, topics, q)

    # starting worker nodes
    for _ in range(THREADPOOL_LIMIT):
        t.execute(create_worker, q)

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/templates/about.html
{% extends "index.html" %}
{% load static %}

{% block appcontent %}
        <!-- ABOUT TEXT -->
        <div class="uk-container uk-container-small uk-flex-auto uk-text-left" data-uk-scrollspy="target: > .animate; cls: uk-animation-slide-bottom-small uk-invisible; delay: 300">
            <article class="uk-article animate uk-invisible">
                <h1 class="uk-article-title">About</h1>
            
                <p class="uk-text-meta"><strong>TECHNOLOGIES USED</strong></p>
                
                <dl class="uk-description-list uk-description-list-divider">
                        <dt class="uk-text-primary">Django</dt>
                        <dd>Django, a Python-based web framework, composes the skeleton of the website.</dd>
                        <dt class="uk-text-primary">Reddit API</dt>
                        <dd>Reddit's API is queried with the user's desired subreddit, returning detailed comment and submission information.</dd>
                        <dt class="uk-text-primary">Google Cloud Natural Language API</dt>
                        <dd>Google's Cloud NLP API is called on cleaned comment text, returning sentiment data to be parsed.</dd>
                </dl>
                <p class="uk-text-small">Note: if all comments show the same number of upvotes, that means the subreddit has set comment scores to be hidden for a period of time after being posted.</p>
            </article>
        </div>
        <!-- / ABOUT TEXT -->

{% endblock %}

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/templates/brand_list.html
{% extends "index.html" %}

{% block appcontent %}

    <h2 class="uk-heading-primary animate uk-invisible" style="font-weight: 500;">List of Brands</h2>
    <div class="uk-width-4-5@m uk-margin-auto animate uk-invisible">

        <table class="styled-table">
        <thead class="table-dark">
            <tr>
                <th scope="col">Topic Name</th>
                <th scope="col">Created At</th>
                <th scope="col">Active</th>
                <th scope="col">Trendline</th>
                <th scope="col">Pause</th>
                <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>

            {% if topics %}
                {% for topic in topics %}
                    <tr>
                        <td><a href={% url 'reddit_sentiment_analyzer:chart' topic.topic_name%}><u>{{ topic.topic_name }}</u></a></td>
                        <td>{{ topic.created_at }}</td>
                        <td>{{ topic.active }}</td>
                        <td><a href={% url 'reddit_sentiment_analyzer:trendline' topic.topic_name%}><u>trendline</u></a></td>

                        {% if topic.active %}
                        <td><a href="{% url 'reddit_sentiment_analyzer:pause_topic' topic.topic_name %}"><i class="fas fa-pause"></i></a></td>
                        {% else %}
                        <td><a href="{% url 'reddit_sentiment_analyzer:pause_topic' topic.topic_name %}"><i class="fas fa-play"></i></a></td>
                        {%  endif %}

                        <td><a href="{% url 'reddit_sentiment_analyzer:delete_topic' topic.topic_name %}"><i class="fas fa-trash-alt"></i></a></td>

                    </tr>
                {% endfor %}

            {% endif %}

        </tbody>
        </table>

    </div>

{% endblock %}

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/templates/chart.html
{% extends "index.html" %}
{% load static %}

{% block appcontent %}
    <div class="uk-flex uk-flex-center uk-flex-middle uk-height-viewport uk-position-z-index uk-position-relative" data-uk-height-viewport="min-height: 400" style="width: 1050px;">

        <!-- TEXT -->
        <div class="uk-container uk-container-small uk-flex-auto uk-text-center" data-uk-scrollspy="target: > .animate; cls: uk-animation-slide-bottom-small uk-invisible; delay: 300">
            <div class="uk-width-4-5@m uk-margin-auto animate uk-invisible">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-4">
                            <canvas id="sentimentChart" width="400" height="400" ></canvas>

                            <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

                            <script>
                                // Retrieve the sentiment percentage value from the Django view
                                var positiveSentiment = {{ sentiment.positive_sentiment }};
                                var negativeSentiment = {{ sentiment.negative_sentiment }};
                                var neutralSentiment = {{ sentiment.neutral_sentiment }};

                                    // Create the pie chart
                                    var ctx = document.getElementById('sentimentChart').getContext('2d');
                                    var chart = new Chart(ctx, {
                                        type: 'pie',
                                        data: {
                                            labels: ['Positive', 'Negative', 'Neutral'],
                                            datasets: [{
                                                data: [positiveSentiment, negativeSentiment, neutralSentiment],
                                                backgroundColor: ['#63ff9a', '#FF6384', '#36A2EB'],
                                            }]
                                        },
                                        options: {
                                            responsive: true,
                                            maintainAspectRatio: false
                                        }
                                    });
                                </script>
                            </div>
                        </div>
                    </div>
            </div>
        </div>


     <div class="uk-container uk-container-small uk-flex-auto uk-text-center" data-uk-scrollspy="target: > .animate; cls: uk-animation-slide-bottom-small uk-invisible; delay: 300" >
        <h2 class="uk-heading-primary animate uk-invisible" style="font-weight: 500;">Streaming Dashboard</h2>

        <h1></h1>
        <div id="data-container" class="scrollable-container">
            <!-- Data will be added here dynamically using JavaScript -->
        </div>

        <!-- Include JavaScript for WebSocket connection -->
        <script>
            const socket = new WebSocket('ws://' + window.location.host + '/ws/reddit_comments/');

            socket.onmessage = function (event) {
                // Process the received data from the server and add it to the dashboard
                console.log('Something received.');
                let data = JSON.parse(event.data);
                console.log(data);
                addDataToDashboard(data);
            };

            // Handle WebSocket connection events
            socket.onopen = function (event) {
                console.log('WebSocket connection established. awesome');

            };



            socket.onclose = function (event) {
                console.log('WebSocket connection closed.');
            };

            // Function to add data to the dashboard
            function addDataToDashboard(data) {
                // Modify this function to display data on the dashboard as needed
                var dataContainer = document.getElementById('data-container');
                dataContainer.innerHTML += '<p>' + JSON.stringify(data) + '</p>';
                dataContainer.scrollTop = dataContainer.scrollHeight;
            }
        </script>
    </div>
    </div>
{% endblock %}

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/templates/index.html
<!doctype html>
{% extends "base.html" %}
{% block content %}
<html>
<head>
    {% load static %}
    <title>Reddit Sentiment</title>
    <link rel="icon" href="img/favicon.ico">
    <style>
        .wrap::before {
            position: absolute;
            height: 150vh;
            width: 100vw;
            content: '';
            z-index: 1;
            background-color: rgba(0,0,0,0.5);
        }
        .lead {
            font-size: 1.175em;
            font-weight: 300;
        }
        .uk-logo img {
            height: 28px;
        }
	</style>

</head>

<body class="uk-light wrap uk-background-norepeat uk-background-cover uk-background-center-center uk-cover-container uk-background-secondary">
    <img src="{% static 'img/274-1200x900-blur_8.jpg' %}" sizes="100vw" alt="" data-uk-cover data-uk-img>
    <div class="uk-flex uk-flex-center uk-flex-middle uk-height-viewport uk-position-z-index uk-position-relative" data-uk-height-viewport="min-height: 400">

        <div class="uk-position-top">
            <div class="uk-container uk-container-small">
                <nav class="uk-navbar-container uk-navbar-transparent" data-uk-navbar>
                    <div class="uk-navbar-left">
                        <div class="uk-navbar-item">
                            <!-- Add the Reddit logo image here -->
                            <a class="uk-logo" href=""><img src="{% static 'img/logo.png' %}" alt="Reddit Logo" style="height:50px; padding:5px;">RedditSentiment</a>
                        </div>
                    </div>
                    <div class="uk-navbar-right">
                        <ul class="uk-navbar-nav">
                            {% if user.is_authenticated %}
                                <li class="uk-active uk-visible@m"><a href={% url 'reddit_sentiment_analyzer:user_home' %} data-uk-icon="home"></a></li>
                                <li class="uk-visible@s"><a href={% url 'reddit_sentiment_analyzer:brand_list' %}>Brand List</a></li>
                                <li class="uk-visible@s"><a href={% url 'reddit_sentiment_analyzer:logout' %}>Logout</a></li>
                            {% else %} 
                                <li class="uk-active uk-visible@m"><a href="/" data-uk-icon="home"></a></li>
                                <li class="uk-visible@s"><a href={% url 'reddit_sentiment_analyzer:register' %}>Register</a></li>
                                <li class="uk-visible@s"><a href={% url 'reddit_sentiment_analyzer:about' %}>About</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
            </div>
        </div>


        <div class="uk-container uk-container-small uk-flex-auto uk-text-center" data-uk-scrollspy="target: > .animate; cls: uk-animation-slide-bottom-small uk-invisible; delay: 300">
                {% block appcontent %} {% endblock %}
        </div>
    </div>
</body>
</html>

{% endblock %}

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/templates/login.html
{% extends "index.html" %}
{% load static %}

{% block appcontent %}

    <h1 class="uk-heading-primary animate uk-invisible" style="font-weight: 500;">Reddit Sentiment Analysis</h1>
    {% if msg %}

    <p>{{msg}}</p>
    {% endif %}
    <form class="uk-margin-medium-top animate uk-invisible" data-uk-margin data-uk-scrollspy-class="uk-animation-fade uk-invisible" method="post">{% csrf_token %}
        <div class="uk-margin">
            {{login_form.as_p}}
        </div>
        <button type="submit" class="uk-button uk-button-default uk-button-large uk-width-2-3 uk-width-auto@s" data-uk-icon="arrow-right" >Login</button>
    </form>
    <p>Don't have an account? <a href="{% url 'reddit_sentiment_analyzer:register' %}">Sign up</a></p>

{%  endblock %}

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/templates/logout.html
<!-- logout.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Logout</title>
</head>
<body>
    <h2>Logged Out Successfully</h2>
    <p>You have been logged out. Thank you for visiting our website.</p>
</body>
</html>

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/templates/trendline.html
{% extends "index.html" %}
{% load static %}

{% block appcontent %}
    <h2>Trendline Analysis Chart</h2>
    <form id="dropdownForm">
        <label for="options">Select a Topic:</label>
        <select name="options" id="options">
            <option value="">Select an option</option>
            {% for option in options %}
                <option value="{{ option.topic_name }}"
                        {% if option == selected_option %}selected{% endif %}>{{ option }}</option>
            {% endfor %}
        </select>
    </form>

    <script>
        // Handle the change event of the drop-down
        document.getElementById('options').addEventListener('change', function () {
            var selectedOption = this.value;
            console.log(selectedOption);
            // Perform redirection based on the selected option
            if (selectedOption !== '') {
                window.location.href = "/trendline/" + selectedOption;
            } else {
                window.location.href = "{% url 'reddit_sentiment_analyzer:trendline' %}"
            }

            // Add more conditions for other options if needed
        });
    </script>

    <br>

    <div>
        <!-- Selection for aggregation -->
        <label for="aggregation">Select Aggregation:</label>
        <select id="aggregation">
            <option value="daily">Daily</option>
            <option value="monthly">Monthly</option>
            <option value="yearly">Yearly</option>
        </select>
    </div>
    <br/>
    <div id="chart-container" style="color: white">
        <!-- The chart will be displayed here -->
        <canvas id="trendlineChart" width="700" height="300"></canvas>
    </div>

    <!-- Include Chart.js library -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        var myChart;

        function destroyChart() {
            if (typeof myChart !== "undefined") {
                myChart.destroy();
            }
        }

        // Function to update the chart data based on aggregation level
        function updateChartData(aggregation) {

            destroyChart();
            var trendlineData = {{ trendline_data|safe }}; // Data from the context
            console.log(trendlineData)
            var chartData;
            if (aggregation === 'daily') {
                chartData = trendlineData.daily;
            } else if (aggregation === 'monthly') {
                chartData = trendlineData.monthly;
            } else if (aggregation === 'yearly') {
                chartData = trendlineData.yearly;
            }

                // Create the chart
            var ctx = document.getElementById("trendlineChart").getContext("2d");
                myChart = new Chart(ctx, {
                    type: "line",
                    data: {
                        labels: chartData.labels,
                        datasets: [{
                            label: "Trendline Data",
                            data: chartData.data,
                            backgroundColor: "rgba(75, 192, 192, 0.2)",
                            borderColor: "rgba(75, 192, 192, 1)",
                            borderWidth: 1,
                            fill: true
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    callback: function (value, index, values) {
                                        // Custom labels for y-axis
                                        if (value === 0) {
                                            return "Neutral";
                                        } else if (value > 0) {
                                            return "Positive";
                                        } else {
                                            return "Negative";
                                        }
                                    }
                                }
                            }
                        }
                    }
                });
        }

        // Handle the change event of the aggregation selection
        document.getElementById('aggregation').addEventListener('change', function () {
            var selectedAggregation = this.value;
            updateChartData(selectedAggregation);
        });

        // Initialize the chart with daily data by default
        updateChartData("daily");
    </script>

    </div>
        <!-- /TEXT -->
{% endblock %}

reddit-sentiment-analysis-master/reddit_sentiment_analyzer/templates/user_home.html
{% extends "index.html" %}
{% load static %}

{% block appcontent %}
    <div class="uk-width-4-5@m uk-margin-auto animate uk-invisible">
        <p class="lead uk-text-secondary">
            {% if user.is_authenticated %}
                Welcome, {{ user.username }}!
            {% endif %}

        </p>       
        <p class="lead uk-text-secondary">Enter a brandname to see the top positive, negative and neutral sentiments</p>
    </div>

    <!-- SUBREDDIT FORM -->
    <form class="uk-margin-medium-top animate uk-invisible" data-uk-margin data-uk-scrollspy-class="uk-animation-fade uk-invisible" method="post" action="{% url 'reddit_sentiment_analyzer:brand_list'%}">{% csrf_token %}
        <div class="uk-margin">
            {{create_topic_form.as_p}}
        </div>
        <button type="submit" class="uk-button uk-button-default uk-button-large uk-width-2-3 uk-width-auto@s" data-uk-icon="arrow-right" >Submit</button>
    </form>
    <!-- SUBREDDIT FORM -->

{% endblock %}